### ISSUE TITLE
Consider using rankmirrors.

### ISSUE THREAD

**Issue by sukalaper** [QuantiniumX/Guide-to-install-Arch-Linux-2023#1]
Does ``reflector`` seem better and faster (IMHO, xD) in this case? I've used both, but somehow only ``rankmirrors`` is able to make me wait until my water boils to make a cup of coffee.

**Comment by quantinium3** [comment]
Whenever rankmirrors took a while i just stopped it in between and ran it again. it worked most of the time. I tried reflector and i think i'll use it too as it increased my download speed. i'll add the reflector part and how both works briefly

**Comment by sukalaper** [comment]
> Whenever rankmirrors took a while i just stopped it in between and ran it again. it worked most of the time. I tried reflector and i think i'll use it too as it increased my download speed. i'll add the reflector part and how both works briefly

OK, maybe that's all. Thanks for the great repo that can help many people install Arch on their machines.🔥
