### ISSUE TITLE
Typo in GRUB_CMDLINE_LINUX

### ISSUE THREAD

**Issue by gundenaf** [QuantiniumX/Guide-to-install-Arch-Linux-2023#2]
Hi! 

It seems there might be a typo here; you need to specify not this 

GRUB_CMDLINE_LINUX="nvidia_drm.modeset=1 rd.driver.blacklist=nouveau modprob.blacklist=nouveau" 

but the next

GRUB_CMDLINE_LINUX="nvidia_drm.modeset=1 rd.driver.blacklist=nouveau modprobe.blacklist=nouveau"

"modprobe.blacklist=nouveau" is the correct option.

https://github.com/QuantiniumX/Guide-to-install-Arch-Linux-2023/blob/main/Graphics/Nvidia.md#step-3---drm-kernel-mode-setting

**Comment by quantinium3** [comment]
Thanks for pointing out the typo.  I've fixed it as per your suggestion.
