### ISSUE TITLE
Add fuse3 to detect bootloader Windows.

### ISSUE THREAD

**Issue by sukalaper** [QuantiniumX/Guide-to-install-Arch-Linux-2023#3]
Hello! Can you add `$ pacman -S fuse3` to detect undetected Windows bootloader? Sorry for the bad screenshot.

![bootloader-windows-fix edited](https://github.com/user-attachments/assets/04ac56ae-74bf-40e8-ba13-64cad8d0ceb5)

**Comment by quantinium3** [comment]
I added it. Here: 3fac11211863380c16f042b31fe93165e9aea94e
